export class Constants{
    public static StartMenuPath: string = ''
    public static AssemblePath: string = 'assemble'
    public static AssembleInsertFootPath: string = 'assemble-insert-foot'
    public static AssembleScrewFootPath: string = 'assemble-screw-foot'
    public static AssembleNeckPath: string = 'assemble-neck'
    public static AssembleHandlebarPath: string = 'assemble-handlebar'
    public static AssembleStemPath: string = 'assemble-stem'
    public static AdjustPath: string = 'adjust'
    public static AdjustExtendAllPath: string = 'adjust-extend-all'
    public static AdjustPlacePhonePath: string = 'adjust-place-phone'
    public static AdjustPullFeetInPath: string = 'adjust-push-feet-in'
    public static AdjustTightenNeckPath: string = 'adjust-tighten-neck'
    public static AdjustLowerFeetPath: string = 'adjust-lower-feet'
    public static MountPath: string = 'mount'
}